app/Http/Controllers/Api/AuthController.php
app/Http/Controllers/MobileApiController.php
routes/api.php

@Michaelndula @Njeri-Ngugi The backend apis connection

Api connection

---

app/Http/Controllers/AdminController.php
public/assets/css/styles.css
resources/views/admin/layout/body.blade.php
resources/views/admin/layout/header.blade.php
resources/views/admin/layout/scripts.blade.php
resources/views/auth/login.blade.php
routes/web.php

Profile modal allowing logout.

Profile and user modal

---

app/Http/Controllers/AdminController.php
public/assets/css/styles.css
resources/views/admin/layout/body.blade.php
resources/views/admin/layout/header.blade.php
resources/views/admin/layout/scripts.blade.php
routes/web.php

User Modal, password input has some bugs

User modal with some bugs

---

app/Http/Controllers/AdminController.php
app/Models/User.php
resources/views/admin/layout/body.blade.php
resources/views/admin/layout/scripts.blade.php
routes/web.php

user modal, still with some bugs

user modal, trying to solve update errors

---

public/assets/css/global.css
resources/views/admin/layout/head.blade.php
resources/views/admin/layout/scripts.blade.php
resources/views/admin/pages/events.blade.php
routes/web.php

@Michaelndula @Njeri-Ngugi  event update & image display function

event update & image display function

---

app/Http/Controllers/AdminController.php
resources/views/admin/layout/scripts.blade.php
resources/views/admin/pages/events.blade.php
routes/web.php

event update @Michaelndula  @Njeri-Ngugi

event update

---

app/Http/Controllers/AdminController.php
resources/views/admin/layout/body.blade.php
resources/views/admin/layout/scripts.blade.php

Update functionality working correctly

User update password and email

---

app/Http/Controllers/AdminController.php
app/Models/Announcement.php
app/Models/SermonNotes.php
public/assets/css/styles.css
resources/views/admin/layout/scripts.blade.php
resources/views/admin/pages/announcements.blade.php
resources/views/admin/pages/sermons-notes.blade.php
resources/views/admin/pages/users.blade.php
routes/web.php

Announcement modal working, sermon-notes modal update has some bugs

Announcement modal

---

app/Http/Controllers/MobileApiController.php
app/Models/Note.php
app/Models/User.php
database/migrations/2024_01_05_065052_create_notes_table.php
routes/api.php

Saving new notes and displaying them on the frontend

GET and POST notes

---

app/Http/Controllers/MobileApiController.php
routes/api.php

Fetching individual sermon

---

app/Http/Controllers/AdminController.php
app/Http/Controllers/Api/AuthController.php
app/Models/AppUser.php
config/auth.php
database/migrations/2014_10_12_000000_create_users_table.php
database/migrations/2024_01_04_055303_create_app_users_table.php
public/assets/js/passwordgenerator.js
resources/views/admin/layout/scripts.blade.php
resources/views/admin/pages/announcements.blade.php
resources/views/admin/pages/sermons-notes.blade.php
resources/views/admin/pages/users.blade.php
routes/api.php
routes/web.php

@Michaelndula @Michaelndula @mathewwahome file conflict four commits behind

file conflict four commits behind

---

app/Http/Controllers/MobileApiController.php
composer.json
composer.lock
config/app.php

PDF display backend

---

app/Http/Controllers/AdminController.php
database/migrations/2014_10_12_000000_create_users_table.php
resources/views/admin/layout/scripts.blade.php
resources/views/admin/pages/settings.blade.php
routes/web.php

@Michaelndula @Njeri-Ngugi  Admin settings new, update & delete user.

Admin settings new, update & delete user.

---

app/Http/Controllers/MobileApiController.php
resources/views/admin/pages/sermons-notes.blade.php

Displaying sermon notes with images and accepting image input

Displaying sermon notes with images and accepting image input

---

.gitignore
app/Http/Controllers/Api/AuthController.php
app/Models/AppUser.php
config/auth.php
config/fortify.php
resources/views/admin/layout/body.blade.php
resources/views/admin/pages/sermons.blade.php

@Michaelndula, signup function

signup function

---

app/Http/Controllers/AdminController.php
resources/views/admin/layout/body.blade.php

@Michaelndula @Njeri-Ngugi  New AppUsers display -

New AppUsers display - 

---

app/Http/Controllers/Api/AuthController.php
app/Http/Controllers/ForgotPasswordController.php
app/Http/Controllers/MobileApiController.php
app/Http/Controllers/ResetPasswordController.php
app/Models/AppUser.php
app/Notifications/CustomResetPasswordNotification.php
config/auth.php
database/migrations/2024_01_10_111629_add_password_reset_token_to_users_table.php
resources/views/auth/password-reset-failed.blade.php
resources/views/auth/password-reset-success.blade.php
resources/views/auth/reset-appuser-password.blade.php
routes/api.php

@Michaelndula @Njeri-Ngugi signup and notes changes

signup and notes changes

---

app/Http/Controllers/MobileApiController.php
routes/api.php

Download function

---

config/jetstream.php
public/assets/css/files.css
public/assets/css/passwordgenerator.css
public/assets/css/styles.css
public/assets/js/modals.js
public/assets/js/scroller.js
resources/views/admin/layout/body.blade.php
resources/views/admin/layout/error.blade.php
resources/views/admin/layout/head.blade.php
resources/views/admin/layout/scripts.blade.php
resources/views/admin/pages/announcements.blade.php
resources/views/admin/pages/events.blade.php
resources/views/admin/pages/sermons-notes.blade.php
resources/views/admin/pages/sermons.blade.php
resources/views/admin/pages/users.blade.php

@Michaelndula @Njeri-Ngugi [Copletion of the scroll function sermons and event]

Copletion of the scroll function sermons and event

---

app/Http/Controllers/Api/AuthController.php
routes/api.php

Update profile function

---

.gitignore
app/Http/Controllers/AdminController.php
public/assets/css/files.css
public/assets/css/global.css
resources/views/admin/layout/header.blade.php
resources/views/admin/pages/events.blade.php
resources/views/admin/pages/profile_page.blade.php
routes/web.php

@Michaelndula @Njeri-Ngugi  admin profile update

admin profile update

---

app/Http/Controllers/MobileApiController.php
routes/api.php

@Michaelndula @Njeri-Ngugi notes_file (notes edit api)

notes_file

---

.gitignore
app/Http/Controllers/MobileApiController.php

@Michaelndula @Njeri-Ngugi git update and displayNotes

git update and displayNotes

---

.gitignore
app/Http/Controllers/AdminController.php
app/Http/Controllers/MobileApiController.php
database/migrations/2023_11_29_082122_create_sermons_table.php
database/migrations/2023_12_04_071756_create_sermon_notes_table.php
public/assets/css/index.css
public/notes_file.json
resources/views/admin/index.blade.php
resources/views/admin/layout/body.blade.php
resources/views/admin/layout/head.blade.php
resources/views/admin/layout/header.blade.php
resources/views/admin/pages/announcements.blade.php
resources/views/admin/pages/sermons-notes.blade.php
resources/views/admin/pages/sermons.blade.php
routes/api.php

@Michaelndula @Njeri-Ngugi notes update sermon notes and the announcements

notes update sermon notes and the announcements

---

app/Http/Controllers/Api/AuthController.php
public/notes_file.json
routes/api.php

@Michaelndula @Njeri-Ngugi  password change

password change

---

public/assets/css/index.css
resources/views/admin/layout/aside.blade.php

@Michaelndula @Njeri-Ngugi  aside bar update

aside bar update

---

app/Http/Controllers/AdminController.php
app/Http/Controllers/Api/AuthController.php
routes/api.php

@Michaelndula @Njeri-Ngugi account deletion and update on the update function.

app user account deletion

---

public/assets/css/index.css
public/assets/js/script.js
resources/views/admin/layout/aside.blade.php
resources/views/admin/layout/header.blade.php

@Michaelndula @Njeri-Ngugi active class update

active class

---

app/Http/Controllers/MobileApiController.php
routes/api.php

@Michaelndula @Njeri-Ngugi user notes deletion

user notes deletion

---

app/Http/Controllers/ForgotPasswordController.php
app/Http/Controllers/ResetPasswordController.php

completion of the code reset password

---

app/Http/Controllers/Api/AuthController.php

user profile picture update to nullable

USER UPDATE

---

app/Http/Controllers/AdminController.php
resources/views/admin/pages/sermons-notes.blade.php

the image was a nullable field @Michaelndula @Njeri-Ngugi

sermon notes update 

---

app/Http/Controllers/Api/AuthController.php
app/Http/Controllers/MobileApiController.php
routes/api.php

Slight modification in sermon data ordering

Slight modification in sermon data ordering
